# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Documentation

on:
  workflow_call:
    inputs:
      artifact_id:
        description: 'Unique identifier for artifacts'
        required: true
        type: string

permissions:
  contents: read

jobs:
  run-trudag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      pull-requests: write
      id-token: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.11.2'

      - name: Install trudag and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          pip install trustable --index-url https://gitlab.com/api/v4/projects/66600816/packages/pypi/simple

      - name: Generate trudag report
        run: |
          TRUDAG_REPORT_FOLDER="TSF/docs/generated"
          mkdir -p "$TRUDAG_REPORT_FOLDER"
          trudag publish --validate --output-dir "$TRUDAG_REPORT_FOLDER"
          trudag plot -o "$TRUDAG_REPORT_FOLDER/graph.svg"
          python TSF/scripts/clean_trudag_output.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload trudag artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: trudag-report-${{ github.event.pull_request.head.sha || github.sha }}
          path: TSF/docs/generated/
          if-no-files-found: error
          
  build-docs:
    needs: run-trudag
    # the eclipse-score/cicd-workflow docs.yml is adjusted to download the trudag report artifact before building the documentation
    uses: ./.github/workflows/docs.yml
    permissions:
      contents: write
      pages: write
      pull-requests: write
      id-token: write

    with:
      # the bazel-target depends on your repo specific docs_targets configuration (e.g. "suffix")Add commentMore actions
      bazel-target: "//:docs -- --github_user=${{ github.repository_owner }} --github_repo=${{ github.event.repository.name }}"
      retention-days: 3
